language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gitbook-cli ebook-convert svgexport
  - sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - sudo apt-get install -y xvfb imagemagick libxcomposite-dev
script:
  - gitbook install && gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _book
  name: "Burke Mamlin"
  email: "burke@openmrs.org"
